### ISSUE TITLE
add Discord 0.0.17.deb

### ISSUE THREAD

**Issue by azur-wolve** [gunalabs/discord-debian-bullseye#2]
Have packed myself it manually using the command:

`dpkg-deb -R discord-0.0.17.deb /tmp/discord-deb && sed -i 's/libappindicator1/libayatana-appindicator1/g' /tmp/discord-deb/DEBIAN/control && dpkg-deb -b /tmp/discord-deb discord-fixed.deb`

It installed correctly but when open it, looks weird:

![Screenshot from 2022-02-17 21-41-25](https://user-images.githubusercontent.com/88264884/154567405-080c08d3-4323-4ee9-b2f0-879e95db1bca.png)

Not sure what's the cause.
Using `sudo` would change anything?

**Comment by gunalabs** [comment]
Hi! 
I'm afraid `sudo` won't change anything (ofc right...)

What you are doing seems fine perfect unless if you check the file sizes.
I tried replicating what you did and checked the file sizes of the deb archive. The original deb file is around 73.5 MiB whereas your resultant deb is around 55.3 MiB.
So, when you are replacing the dependency and repacking using `dpkg-deb`, it should be replacing the libraries and much of dependencies for the new one, discarding some from the old one. This ends up in less stuffs than the `libappindicator1` but those are probably required by discord and hence the UI breaks.
So, what we need to do is, rather replacing the dependency, we only need to rename in the `control` file which will change nothing but only that name.

**Comment by gunalabs** [comment]
Kindly check with the update and say!

**Comment by gunalabs** [comment]
Currently closing this issue hoping its resolved.
